### ISSUE TITLE
prepend   bug?

### ISSUE THREAD

**Issue by fitan** [jianfengye/collection#16]
![image](https://user-images.githubusercontent.com/34503273/61631102-11902800-acbc-11e9-8642-a6bcce183e4d.png)

![image](https://user-images.githubusercontent.com/34503273/61631123-1bb22680-acbc-11e9-97dd-ed5e6236143c.png)
这个是不是  一个bug 啊

**Comment by jianfengye** [comment]
谢谢提醒，已经修复了
