### ISSUE TITLE
map 方法 bug

### ISSUE THREAD

**Issue by fitan** [jianfengye/collection#18]
![image](https://user-images.githubusercontent.com/34503273/61776684-1b399d00-ae2e-11e9-9222-2871dc725d49.png)
根据第一个 字符 判断类型生成 数组 但是   obj  可能是[]interface  生成的是 是普通类型的。 
还有这个方法没有continue 部分 func 返回 两个 参数 一个事data 一个是 bool  bool判断是否continue

**Comment by jianfengye** [comment]
请看看最新提交： https://github.com/jianfengye/collection/commit/60e484416dbb684f3f969b990da59d4e1efe1133
1 处理了contine问题，但是不是使用增加bool参数，而是判断返回是否nil
2 map不使用第一个字符判断，先计算出[]interface{} 再生成对应的Collection

**Comment by fitan** [comment]
我觉得 还是需要多些几篇文档 多在几个平台上发发。这样用的人多了，反馈也就多了。
