### ISSUE TITLE
First(...func(item interface{}, key int) bool) IMix逻辑问题

### ISSUE THREAD

**Issue by zlyuancn** [jianfengye/collection#20]
First(...func(item interface{}, key int) bool) IMix
如果我传入两个函数进去, 第一个函数无论如何都返回false, 那么第二个函数有什么意义?

**Comment by zlyuancn** [comment]
按照逻辑来说, 第一个函数无法满足条件, 那么久开始第二个函数来查找, 然而你的代码并没有对之后的函数做处理

**Comment by jianfengye** [comment]
这个函数传进来的f是0个或者1个，并不是允许传递多个过滤函数。如果传递0个过滤函数，就返回数组中的第一个元素。

感谢提醒，已经增加文档说明：https://github.com/jianfengye/collection/commit/53f992706f81069da6fddc75a68b2a55158b4747
