### ISSUE TITLE
/collection@v1.3.0/abs_array.go:957 报超出索引错误

### ISSUE THREAD

**Issue by mickycm** [jianfengye/collection#25]
/collection@v1.3.0/abs_array.go:957 有时会报错;
Handler crashed with error runtime error: index out of range [4041] with length 4041
以下代码,如果这个[]string  一直变化 的话, 超长是不是就报错了?
func (arr *AbsCollection) ToStrings() ([]string, error) {
	if arr.Err() != nil {
		return nil, arr.Err()
	}

	ret := make([]string, arr.Count())
	for i := 0; i < arr.Count(); i++ {
		t, err := arr.Index(i).ToString()
		if err != nil {
			return nil, err
		}
		ret[i] = t
	}
	return ret, nil
}

改成如下:?
func (arr *AbsCollection) ToStrings() ([]string, error) {
	if arr.Err() != nil {
		return nil, arr.Err()
	}

	size := arr.Count()
	ret := make([]string, size)

	for i := 0; i < size; i++ {
		t, err := arr.Index(i).ToString()
		if err != nil {
			return nil, err
		}
		ret[i] = t
	}
	return ret, nil
}

**Comment by jianfengye** [comment]
你是说还有另外一个线程，在修改arr的长度是么？那arr.Count是有可能报错的。但是线程安全就是另外一个事情了，这样修改也没有办法解决线程安全的问题

**Comment by jianfengye** [comment]
关于这个错误：Handler crashed with error runtime error: index out of range [4041] with length 4041  你能写个bad case 么
