### ISSUE TITLE
请教一个线程安全问题

### ISSUE THREAD

**Issue by 1984anonymous** [jianfengye/collection#31]
golang 并发对切片进行 append 会有线程安全问题，在使用 collection 的时候， 如需规避这个问题，是不是在每次调用 append 的时候都需要加锁呢，例如：
```golang
 var lock sync.Mutex

 lock.Lock()
 collection.append(...)
 lock.Unlock()
```
除了在 collection 中 使用 append 之外，其他的方法在使用的时候是不是也需要注意线程安全的问题，因为我好像没在源码中看到有任何使用到锁的地方。

**Comment by jianfengye** [comment]
是会有线程安全问题，这个库没有考虑线程并发
