### ISSUE TITLE
结构体数组如何实现筛选

### ISSUE THREAD

**Issue by ityc** [jianfengye/collection#4]
````golang
[]TutorList{
TutorList{Pid:1, Realname:"陈老师", Remark:"", Grade:80}, 
TutorList{Pid:3, Realname:"陈老师", Remark:"", Grade:60}, 
TutorList{Pid:3, Realname:"陈老师", Remark:"", Grade:70}, 
TutorList{Pid:4, Realname:"陈老师", Remark:"", Grade:95}
}
````

现有上面的结构体数组,请问如何实现筛选?
例如 指定 `TutorList.Pid=3` 得到
````golang
[]TutorList{
TutorList{Pid:3, Realname:"陈老师", Remark:"", Grade:60}, 
TutorList{Pid:3, Realname:"陈老师", Remark:"", Grade:70}, 
}
````

**Comment by jianfengye** [comment]
`
package main

import (
	"github.com/jianfengye/collection"
)

type TutorList struct {
	Pid int
	Realname string
	Remark string
	Grade int
}

func main() {
	arr := []TutorList{
		TutorList{Pid:1, Realname:"陈老师", Remark:"", Grade:80},
		TutorList{Pid:3, Realname:"陈老师", Remark:"", Grade:60},
		TutorList{Pid:3, Realname:"陈老师", Remark:"", Grade:70},
		TutorList{Pid:4, Realname:"陈老师", Remark:"", Grade:95},
	}
	objArr := collection.NewObjCollection(arr)
	objArr.Filter(func(obj interface{}, index int) bool {
		t := obj.(TutorList)
		if t.Pid == 3 {
			return true
		}
		return false
	}).DD()
}

`

**Comment by ityc** [comment]
谢谢,我再看看,现在主要是在考虑性能问题
